### ISSUE TITLE
Could not find SDL2TTF

### ISSUE THREAD

**Issue by Anonymous3-a** [kongaskristjan/PhaseTransfer#1]
I tried to build it, but got this error:

```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find SDL2TTF (missing: SDL2TTF_LIBRARY SDL2TTF_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSDL2TTF.cmake:163 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:13 (find_package)
```
I can attach the log if needed

**Comment by kristjanveeve** [comment]
Do you have SDL2TTF installed? Also, what operating system are you using?

**Comment by kongaskristjan** [comment]
Do you have SDL2TTF development package installed? Also, what operating system are you using?

**Comment by Anonymous3-a** [comment]
I don't know what SDL2TTF is, so probably not, and Arch GNU/Linux

**Comment by kongaskristjan** [comment]
Well, googling "sdl2ttf arch" reveals [this package](https://archlinux.org/packages/extra/x86_64/sdl2_ttf/) as the first result. Try installing this.

**Comment by Anonymous3-a** [comment]
Oh, I guess I missed that in pacman -Ss, but thanks anyway!
